CREATE TABLE LUGAR(
     id SERIAL,
     nombre VARCHAR (50) NOT NULL,
     tipo VARCHAR (50) NOT NULL,
     LUGAR_id INTEGER,

     CONSTRAINT LUGAR_PK PRIMARY KEY (id),

     CONSTRAINT LUGAR_LUGAR_FK FOREIGN KEY( LUGAR_id ) REFERENCES LUGAR( id ),

     CONSTRAINT LUGAR_CH CHECK ( tipo IN ('Direccion', 'Ciudad', 'Estado', 'Pais') )
);


CREATE TABLE INTERES(
     id SERIAL,
     nombre VARCHAR (50) NOT NULL,
     descripcion VARCHAR (100) NOT NULL,

     CONSTRAINT INTERES_PK PRIMARY KEY  (id)
);


CREATE TABLE CLUB(
     id SERIAL,
     fecha_fundacion DATE NOT NULL,
     telefono NUMERIC(15) NOT NULL,
     pagina_web VARCHAR (50),
     proposito VARCHAR (50),
     MEMBRESIA_COLECCIONISTA_documento_identidad NUMERIC(10) NOT NULL,
     MEMBRESIA_CLUB_id INTEGER NOT NULL,
     MEMBRESIA_fecha_ingreso DATE NOT NULL,
     LUGAR_id INTEGER NOT NULL,

     CONSTRAINT CLUB_PK PRIMARY KEY (id),
     CONSTRAINT CLUB_LUGAR_FK FOREIGN KEY( LUGAR_id ) REFERENCES LUGAR( id )
);


CREATE TABLE CLU_INT(
     INTERES_id INTEGER NOT NULL,
     CLUB_id INTEGER NOT NULL,

     CONSTRAINT CLU_INT_PK PRIMARY KEY  (INTERES_id, CLUB_id),

     CONSTRAINT CLU_INT_CLUB_FK FOREIGN KEY( CLUB_id ) REFERENCES CLUB( id ) ,
     CONSTRAINT CLU_INT_INTERES_FK FOREIGN KEY( INTERES_id ) REFERENCES INTERES( id )
);


CREATE TABLE REPRESENTANTE(
     documento_identidad NUMERIC(10) NOT NULL,
     nombre VARCHAR (25) NOT NULL,
     apellido VARCHAR (25) NOT NULL,
     fecha_nacimiento DATE NOT NULL,

     CONSTRAINT REPRESENTANTE_PK PRIMARY KEY  (documento_identidad) 
);


CREATE TABLE COLECCIONISTA(
     documento_identidad NUMERIC(10) NOT NULL,
     primer_nombre VARCHAR (50) NOT NULL,
     segundo_nombre VARCHAR (50),
     primer_apellido VARCHAR (50) NOT NULL,
     segundo_apellido VARCHAR (50),
     telefono NUMERIC(15) NOT NULL,
     fecha_nacimiento DATE NOT NULL,
     LUGAR_id_nacionalidad INTEGER NOT NULL,
     COLECCIONISTA_documento_identidad INTEGER,
     REPRESENTANTE_documento_identidad INTEGER,
     LUGAR_id_direccion INTEGER NOT NULL,

     CONSTRAINT COLECCIONISTA_PK PRIMARY KEY (documento_identidad),

     CONSTRAINT COLECCIONISTA_COLECCIONISTA_FK FOREIGN KEY( COLECCIONISTA_documento_identidad ) REFERENCES COLECCIONISTA( documento_identidad ),
     CONSTRAINT COLECCIONISTA_LUGAR_FK FOREIGN KEY( LUGAR_id_direccion ) REFERENCES LUGAR( id ),
     CONSTRAINT COLECCIONISTA_LUGAR_FKv2 FOREIGN KEY( LUGAR_id_nacionalidad ) REFERENCES LUGAR( id ),
     CONSTRAINT COLECCIONISTA_REPRESENTANTE_FK FOREIGN KEY( REPRESENTANTE_documento_identidad ) REFERENCES REPRESENTANTE( documento_identidad ) ON DELETE cascade,

     CONSTRAINT COLECCIONISTA_AR CHECK (( ( representante_documento_identidad IS NOT NULL ) AND ( coleccionista_documento_identidad IS NULL ) )
                                      OR( ( coleccionista_documento_identidad IS NOT NULL ) AND ( representante_documento_identidad IS NULL ) )
                                          OR( ( representante_documento_identidad IS NULL ) AND ( coleccionista_documento_identidad IS NULL ) ) )


);


CREATE TABLE CONTACTO(
     id SERIAL,
     usuario_email VARCHAR (50),
     telefono NUMERIC(15),
     plataforma VARCHAR (50) NOT NULL,
     CLUB_id INTEGER NOT NULL,

     CONSTRAINT CONTACTO_PK PRIMARY KEY  (CLUB_id, id),
     CONSTRAINT CONTACTO_CLUB_FK FOREIGN KEY( CLUB_id ) REFERENCES CLUB( id )
);


CREATE TABLE COLECCIONABLE(
     id SERIAL,
     nombre VARCHAR (50) NOT NULL,
     descripcion_detallada VARCHAR (100) NOT NULL,

     CONSTRAINT COLECCIONABLE_PK PRIMARY KEY  (id)
);


CREATE TABLE COMIC(
     id SERIAL,
     titulo VARCHAR (50) NOT NULL,
     volumen NUMERIC(10),
     numero NUMERIC(10) NOT NULL,
     fecha_publicacion DATE NOT NULL,
     precio_publicacion REAL,
     color BOOLEAN NOT NULL,
     sinopsis VARCHAR (1000) NOT NULL,
     paginas NUMERIC(10) NOT NULL,
     cubierta BOOLEAN NOT NULL,
     editor VARCHAR (50) NOT NULL,

     CONSTRAINT COMIC_PK PRIMARY KEY  (id)
);


CREATE TABLE DUENO_HISTORICO(
     id SERIAL,
     fecha_registro DATE NOT NULL,
     significado VARCHAR (50),
     COLECCIONISTA_documento_identidad NUMERIC(10) NOT NULL,
     COLECCIONABLE_id INTEGER,
     precio_dolar REAL,
     COMIC_id INTEGER,

     CONSTRAINT DUENO_HISTORICO_PK PRIMARY KEY  (COLECCIONISTA_documento_identidad, fecha_registro, id),

     CONSTRAINT DUENO_HISTORICO_COLECCIONABLE_FK FOREIGN KEY( COLECCIONABLE_id ) REFERENCES COLECCIONABLE( id ),
     CONSTRAINT DUENO_HISTORICO_COLECCIONISTA_FK FOREIGN KEY( COLECCIONISTA_documento_identidad ) REFERENCES COLECCIONISTA( documento_identidad ),
     CONSTRAINT DUENO_HISTORICO_COMIC_FK FOREIGN KEY( COMIC_id ) REFERENCES COMIC( id ),

     CONSTRAINT DUENO_HISTORICO_AR CHECK ( (  (COMIC_id IS NOT NULL) AND (COLECCIONABLE_id IS NULL) )
                                OR (  (COLECCIONABLE_id IS NOT NULL) AND (COMIC_id IS NULL) ))

);


CREATE TABLE LOCAL(
     id SERIAL,
     nombre VARCHAR (50) NOT NULL,
     alquilado BOOLEAN NOT NULL,
     LUGAR_id INTEGER NOT NULL,
     COLECCIONISTA_documento_identidad INTEGER,
     tipo VARCHAR (50) NOT NULL,

     CONSTRAINT LOCAL_PK PRIMARY KEY  (id),

     CONSTRAINT LOCAL_COLECCIONISTA_FK FOREIGN KEY( COLECCIONISTA_documento_identidad ) REFERENCES COLECCIONISTA( documento_identidad ),
     CONSTRAINT LOCAL_LUGAR_FK FOREIGN KEY( LUGAR_id ) REFERENCES LUGAR( id ),

     CONSTRAINT LOCAL_CH CHECK ( tipo IN ('Alquilado', 'De un Miembro') )
);


CREATE TABLE MEMBRESIA(
     fecha_ingreso DATE NOT NULL,
     fecha_retiro DATE,
     CLUB_id INTEGER NOT NULL,
     CLUB_id_lider INTEGER,
     COLECCIONISTA_documento_identidad NUMERIC(10) NOT NULL,
     email_contacto VARCHAR (50),

     CONSTRAINT MEMBRESIA_PK PRIMARY KEY (COLECCIONISTA_documento_identidad, CLUB_id, fecha_ingreso),

     CONSTRAINT MEMBRESIA_CLUB_FK FOREIGN KEY( CLUB_id ) REFERENCES CLUB( id ) ,
     CONSTRAINT MEMBRESIA_CLUB_FK_LIDER FOREIGN KEY( CLUB_id_lider ) REFERENCES CLUB( id ),
     CONSTRAINT MEMBRESIA_COLECCIONISTA_FK FOREIGN KEY( COLECCIONISTA_documento_identidad ) REFERENCES COLECCIONISTA( documento_identidad )
);


CREATE TABLE ORGANIZACION_CARIDAD(
     id SERIAL,
     nombre VARCHAR (50) NOT NULL,
     mision VARCHAR (50) NOT NULL,

     CONSTRAINT ORGANIZACION_CARIDAD_PK PRIMARY KEY (id)
);


CREATE TABLE SUBASTA(
     id SERIAL,
     fecha DATE NOT NULL,
     hora_inicio TIME NOT NULL,
     hora_cierre TIME NOT NULL,
     tipo VARCHAR (50) NOT NULL,
     caridad BOOLEAN NOT NULL,
     cancelado BOOLEAN NOT NULL,
     LOCAL_id INTEGER NOT NULL,

     CONSTRAINT SUBASTA_PK PRIMARY KEY  (id),
     CONSTRAINT SUBASTA_CH CHECK ( tipo IN ('Presencial', 'Virtual') ),

     CONSTRAINT SUBASTA_LOCAL_FK FOREIGN KEY( LOCAL_id ) REFERENCES LOCAL(id)
     
);


CREATE TABLE PARTICIPANTE(
     id_inscripcion INTEGER NOT NULL,
     SUBASTA_id INTEGER NOT NULL,
     MEMBRESIA_COLECCIONISTA_documento_identidad NUMERIC(10) NOT NULL,
     MEMBRESIA_CLUB_id INTEGER NOT NULL,
     MEMBRESIA_fecha_ingreso DATE NOT NULL,
     autorizado BOOLEAN,

     CONSTRAINT PARTICIPANTE_PK PRIMARY KEY (SUBASTA_id, id_inscripcion),

     CONSTRAINT PARTICIPANTE_MEMBRESIA_FK FOREIGN KEY( MEMBRESIA_COLECCIONISTA_documento_identidad, MEMBRESIA_CLUB_id, MEMBRESIA_fecha_ingreso ) REFERENCES MEMBRESIA( COLECCIONISTA_documento_identidad, CLUB_id, fecha_ingreso ),
     CONSTRAINT PARTICIPANTE_SUBASTA_FK FOREIGN KEY( SUBASTA_id ) REFERENCES SUBASTA( id )
);


CREATE TABLE ORG_INV(
     id SERIAL,
     SUBASTA_id INTEGER NOT NULL,
     CLUB_id_org INTEGER,
     CLUB_id_inv INTEGER,

     CONSTRAINT ORG_INV_PK PRIMARY KEY  (id, SUBASTA_id),

     CONSTRAINT ORG_INV_CLUB_FK FOREIGN KEY( CLUB_id_org ) REFERENCES CLUB( id ) ,
     CONSTRAINT ORG_INV_CLUB_FKv2 FOREIGN KEY( CLUB_id_inv ) REFERENCES CLUB( id ) ,
     CONSTRAINT ORG_INV_SUBASTA_FK FOREIGN KEY( SUBASTA_id ) REFERENCES SUBASTA( id ),

     CONSTRAINT ORG_INV_AR CHECK ( (  (CLUB_id_org IS NOT NULL) AND (CLUB_id_inv IS NULL) )
                                OR(  (CLUB_id_inv IS NOT NULL) AND (CLUB_id_org IS NULL) ) )

);


CREATE TABLE ORG_SUB(
     porcentaje NUMERIC(10) NOT NULL,
     monto_recibido REAL,
     ORGANIZACION_CARIDAD_id INTEGER NOT NULL,
     SUBASTA_id INTEGER NOT NULL,

     CONSTRAINT ORG_SUB_PK PRIMARY KEY  (ORGANIZACION_CARIDAD_id, SUBASTA_id),

     CONSTRAINT ORG_SUB_ORGANIZACION_CARIDAD_FK FOREIGN KEY( ORGANIZACION_CARIDAD_id ) REFERENCES ORGANIZACION_CARIDAD( id ),
     CONSTRAINT ORG_SUB_SUBASTA_FK FOREIGN KEY( SUBASTA_id ) REFERENCES SUBASTA( id )
);


CREATE TABLE LISTADO(
     id SERIAL,
     orden NUMERIC(10),
     precio_base_dolar REAL NOT NULL,
     precio_vendido_dolar REAL,
     SUBASTA_id INTEGER NOT NULL,
     DUENO_HISTORICO_COLECCIONISTA_documento_identidad NUMERIC(10) NOT NULL,
     DUENO_HISTORICO_fecha_registro DATE NOT NULL,
     PARTICIPANTE_subasta_id INTEGER,
     DUENO_HISTORICO_id INTEGER NOT NULL,
     PARTICIPANTE_id_inscripcion INTEGER,

     CONSTRAINT LISTADO_PK PRIMARY KEY  (SUBASTA_id, id),

     CONSTRAINT LISTADO_DUENO_HISTORICO_FK FOREIGN KEY( DUENO_HISTORICO_COLECCIONISTA_documento_identidad, DUENO_HISTORICO_fecha_registro, DUENO_HISTORICO_id ) REFERENCES DUENO_HISTORICO( COLECCIONISTA_documento_identidad, fecha_registro, id ),
     CONSTRAINT LISTADO_PARTICIPANTE_FK FOREIGN KEY( PARTICIPANTE_subasta_id, PARTICIPANTE_id_inscripcion ) REFERENCES PARTICIPANTE( SUBASTA_id, id_inscripcion ),
     CONSTRAINT LISTADO_SUBASTA_FK FOREIGN KEY( SUBASTA_id ) REFERENCES SUBASTA( id )
);
