INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Venezuela', 'Pais', NULL);
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('USA', 'Pais', NULL);
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Francia', 'Pais', NULL);
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Japon', 'Pais', NULL);
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Distrito Capital', 'Estado', '1');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Miranda', 'Estado', '1');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Florida', 'Estado', '2');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('New York', 'Estado', '2');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Ile-de-France', 'Estado', '3');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Occitanie', 'Estado', '3');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Tokio', 'Estado', '4');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Kyoto', 'Estado', '4');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Caracas', 'Ciudad', '5');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Los Teques', 'Ciudad', '6');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Miami', 'Ciudad', '7');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('New York', 'Ciudad', '8');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Paris', 'Ciudad', '9');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Toulouse', 'Ciudad', '10');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Tokio', 'Ciudad', '11');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Kyoto', 'Ciudad', '12');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Calle Paris, Edif. La Joya', 'Direccion', '13');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Ave. Libertador, C.C. Sambil', 'Direccion', '13');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Calle Boyaca, El Rosal', 'Direccion', '13');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Calle El Estanque, La Florida', 'Direccion', '13');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('4ta. Transversal, Altamira', 'Direccion', '13');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Ave. Principal de Los Ruices', 'Direccion', '13');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Av. La Hoyada, C.C. La Hoyada', 'Direccion', '14');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Calle Junin', 'Direccion', '14');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Calle Guaicaipuro', 'Direccion', '14');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('17 SW 7th St', 'Direccion', '15');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('16 NW 15th ST', 'Direccion', '15');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('95 Madison Ave', 'Direccion', '16');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('15 Concord Ave', 'Direccion', '16');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Quai de Grands Augustins 15', 'Direccion', '17');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Rue Daguerre 5', 'Direccion', '17');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('8 Rue de Metz', 'Direccion', '18');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('14 Rue Gaston Salvayre', 'Direccion', '18');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('1 Chome-8-13 Nihonbashihoridomecho', 'Direccion', '19');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('5 Chuo-dori Ave', 'Direccion', '19');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('5 Kujo-dori St', 'Direccion', '20');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('12 Nishikujo Inmachi', 'Direccion', '20');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Ave. Venezuela, El Rosal', 'Direccion', '13');
INSERT INTO lugar (nombre, tipo, lugar_id) VALUES ('Rusia', 'Pais', NULL);

INSERT INTO interes (nombre, descripcion) VALUES ('Consola Nintendo 64', 'Controles, juegos, accessorios y ediciones limitadas de la consola Nintendo 64');
INSERT INTO interes (nombre, descripcion) VALUES ('Tetris', 'Juego Clasico desde 1984');
INSERT INTO interes (nombre, descripcion) VALUES ('Juego PS1 y PS2', 'Lo mejor en juegos de la 5ta y 6ta generacion de consolas de Sony');
INSERT INTO interes (nombre, descripcion) VALUES ('Star Wars', 'Que la Fuerza nos acompane');
INSERT INTO interes (nombre, descripcion) VALUES ('PC Gaming', 'A por la PC Master Race');
INSERT INTO interes (nombre, descripcion) VALUES ('Xbox', 'Microsoft de verdad tiene una consola, no solo es Windows en otro hardware');
INSERT INTO interes (nombre, descripcion) VALUES ('Arcade', 'Por los viejos tiempos y los nuevos');
INSERT INTO interes (nombre, descripcion) VALUES ('MMORPG', 'Por la Horda, la Alianza, Eorzea y muchos mas');
INSERT INTO interes (nombre, descripcion) VALUES ('Role-Play', 'NO es lo que piensan');

INSERT INTO club (fecha_fundacion, telefono, pagina_web, proposito, lugar_id, nombre) VALUES ('5/28/2018', '9510162', 'www.zendikar.com.ve', 'Mayor centro de coleccionistas de Caracas', '21', 'Zendikar')
INSERT INTO club (fecha_fundacion, telefono, pagina_web, proposito, lugar_id, nombre) VALUES ('11/20/2014', '9865412', 'www.asmodeus.com', 'Enfocados en las mejores subastas de Comics y Videojuegos', '22', 'Asmodeus')
INSERT INTO club (fecha_fundacion, telefono, pagina_web, proposito, lugar_id, nombre) VALUES ('2/4/2016', '123457820', NULL, 'Miamis Gaming Hub', '30', 'The GameHub')
INSERT INTO club (fecha_fundacion, telefono, pagina_web, proposito, lugar_id, nombre) VALUES ('7/8/2015', '852456321', 'www.theempire.com', 'The domain of the Geeks', '32', 'The Empire')
INSERT INTO club (fecha_fundacion, telefono, pagina_web, proposito, lugar_id, nombre) VALUES ('8/21/2009', '8529674', 'www.cathedrale.co.fr', 'La Religion Nerd', '34', 'Le Cathedrale')
INSERT INTO club (fecha_fundacion, telefono, pagina_web, proposito, lugar_id, nombre) VALUES ('8/15/2019', '7895410', 'www.limsalominsa.com', 'Le Vrai ComicCon', '36', 'Limsa Lominsa')
INSERT INTO club (fecha_fundacion, telefono, pagina_web, proposito, lugar_id, nombre) VALUES ('4/16/2017', '95145320', 'www.hingashi.com', 'We love RPG', '38', 'Hingashi')
INSERT INTO club (fecha_fundacion, telefono, pagina_web, proposito, lugar_id, nombre) VALUES ('9/10/2014', '84512639', 'www.kuganecc.co.jp', 'Comic and Videogame Haven', '40', 'Kugane')
INSERT INTO club (fecha_fundacion, telefono, pagina_web, proposito, lugar_id, nombre) VALUES ('2/3/2005', '7894512', 'www.lacueva.com.ve', 'Donde se consuige el amor al comic', '42', 'La Cueva')

INSERT INTO representante (documento_identidad, nombre, apellido, fecha_nacimiento) VALUES ('8529674', 'Jose', 'Perez', '8/7/1984');
INSERT INTO representante (documento_identidad, nombre, apellido, fecha_nacimiento) VALUES ('7418596', 'Maria', 'Ramirez', '9/7/1998');
INSERT INTO representante (documento_identidad, nombre, apellido, fecha_nacimiento) VALUES ('9513265', 'Pablo', 'de San Martin', '4/7/1990');
INSERT INTO representante (documento_identidad, nombre, apellido, fecha_nacimiento) VALUES ('2435768', 'Sara', 'Valladolid', '9/9/1999');
INSERT INTO representante (documento_identidad, nombre, apellido, fecha_nacimiento) VALUES ('23456789', 'Marcello', 'Viera', '8/10/1885');
INSERT INTO representante (documento_identidad, nombre, apellido, fecha_nacimiento) VALUES ('12456789', 'Andreas', 'Sarmiento', '9/9/1888');
INSERT INTO representante (documento_identidad, nombre, apellido, fecha_nacimiento) VALUES ('123456', 'Sarah', 'Connor', '7/7/1987');
INSERT INTO representante (documento_identidad, nombre, apellido, fecha_nacimiento) VALUES ('456123', 'Michael', 'Cane', '3/3/1985');
INSERT INTO representante (documento_identidad, nombre, apellido, fecha_nacimiento) VALUES ('456789', 'Yuri', 'Gagarin', '6/6/1985');

INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('25385914', 'Jose', 'Luis', 'Gil', 'Zamora', '4265558822', '6/30/1996', '1', NULL, NULL, '23'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('5222910', 'Maria', 'Salome', 'Zamora', NULL, '9531228', '5/28/1976', '1', NULL, NULL, '23'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('28314614', 'Gabriel', 'Jose', 'Gil', NULL, '4265874123', '11/9/2001', '1', NULL, NULL, '23'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('14000000', 'Alisaie', 'Yshtola', 'Levelieur', NULL, '9568741', '12/12/1990', '3', NULL, NULL, '35'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('3000000', 'Isaac', NULL, 'Asimov', NULL, '7996543258', '9/9/1988', '2', NULL, NULL, '31'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('1234567', 'Hideo', NULL, 'Kojima', NULL, '1234567845', '16/8/1974', '4', NULL, NULL, '41'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('2345678', 'Shigeru', NULL, 'Miyamoto', NULL, '74152965', '8/13/1978', '4', NULL, NULL, '39'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('14725836', 'John', 'Phillip', 'Carmack', NULL, '789654123', '8/9/1987', '2', NULL, NULL, '33'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('25836914', 'Gabe', 'Daniel', 'Newell', NULL, '852147896', '11/10/1978', '2', NULL, NULL, '28'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('1998456', 'Alexey', 'Leonidovij', 'Pajitnov', NULL, '838635954', '9/15/1991', '43', NULL, NULL, '29'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('12345698', 'Shinji', NULL, 'Mikami', NULL, '8745213654', '12/5/1992', '4', NULL, NULL, '24'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('14000001', 'Alphinaud', NULL, 'Levelieur', NULL, '12345678', '2/2/2005', '3', '14000000', NULL, '35'); 
INSERT INTO  coleccionista (documento_identidad, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, telefono, fecha_nacimiento, lugar_id_nacionalidad, coleccionista_documento_identidad, representante_documento_identidad, lugar_id_direccion) VALUES ('12987456', 'John', NULL, 'Connor', NULL, '1239854', '3/3/2005', '2', NULL, '123456', '25'); 

INSERT INTO contacto (uauario_email, telefono, plataforma, club_id) VALUES (NULL, NULL, 'Twitter', '1');
INSERT INTO contacto (uauario_email, telefono, plataforma, club_id) VALUES (NULL, NULL, 'Facebook', '2');
INSERT INTO contacto (uauario_email, telefono, plataforma, club_id) VALUES (NULL, NULL, 'Instagram', '3');
INSERT INTO contacto (uauario_email, telefono, plataforma, club_id) VALUES (NULL, '45678921', 'Telefono', '4');
INSERT INTO contacto (uauario_email, telefono, plataforma, club_id) VALUES ('contact@lecathedrale.fr', NULL, 'Email', '5');
INSERT INTO contacto (uauario_email, telefono, plataforma, club_id) VALUES (NULL, NULL, 'Facebook', '6');
INSERT INTO contacto (uauario_email, telefono, plataforma, club_id) VALUES (NULL, NULL, 'Facebook', '7');
INSERT INTO contacto (uauario_email, telefono, plataforma, club_id) VALUES (NULL, NULL, 'Instagram', '8');
INSERT INTO contacto (uauario_email, telefono, plataforma, club_id) VALUES (NULL, NULL, 'Twitter', '9');

INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Major Motoko Kusanagi', 'Figura de la protagonista de Ghost in the Shell');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Mario Bros.', 'Figura live-size de los personajes de Mario Bros');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Final Fantasy VII OST', 'Disco de vinilo de la banda sonora de Final Fantasy');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Arcade de Pac-Man', 'Maquina de Arcade Original de Pacman');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Doom', 'Videojuego Clasico sellado en su caja');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Tifa Lockhart', 'Figura del personaje de Final Fantasy VII');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Cloud Strife', 'Figura del personaje de Final Fantasy VII');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Aerith Gainsborough', 'Figura del personaje de Final Fantasy VII');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Sephirot', 'Figura del personaje de Final Fantasy VII');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Jaina Proudmore', 'Figura del personaje de World of Warcraft');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Garrosh', 'Figura del personaje de World of Warcraft');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Lich King', 'Figura del personaje de World of Warcraft');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Terra Bradfort', 'Figura del personaje de Final Fantasy VI');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Loke', 'Figura del personaje de Final Fantasy VI');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Tomb Raider', 'Juego de 1996 para el Sega Genesys');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Lara Croft', 'Figura del personaje de Tomb Raider');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Sonic the Hedgehog', 'Primer juego del famoso erizo azul');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Sega Genesys', 'Legendaria Consola de Sega sellada en su caja');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Nes', 'Nintendo Entertainment System sellado en su caja');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('SNES', 'Super Nintendo Entertainment System sellado en su caja');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Nintendo GameCube', 'Nintendo GameCube sellado en su caja');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Nintendo 64', 'Nintendo 64 sellado en su caja');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Pokemon Red and Green', 'Primeros juegos de Pokemon en japones sellados en su caja');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Son Goku Firmada', 'Figura del protagonista de Dragon Ball firmada por el Autor');
INSERT INTO coleccionable (nombre, descripcion_detallada) VALUES ('Figura de Los Cuatros Fantasticos firmada', 'Figura de los Cuatro Fantasticos, firmada por Jack Kirby y Stan Lee');

INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '25385914', '1', NULL, '20');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '5222910', '2', NULL, '120');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '28314614', '3', NULL, '58');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14000000', '4', NULL, '550');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '3000000', '5', NULL, '26');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '1234567', '6', NULL, '900');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '2345678', '7', NULL, '874');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14725836', '8', NULL, '865');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '25836914', '9', NULL, '4123');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '1998456', '10', NULL, '9874');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '12345698', '11', NULL, '352');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14000001', '12', NULL, '325');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '12987456', '13', NULL, '126');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '25385914', '14', NULL, '754');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '5222910', '15', NULL, '865');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '28314614', '16', NULL, '3257');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14000000', '17', NULL, '2147');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '3000000', '18', NULL, '9853');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '1234567', '19', NULL, '125');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '2345678', '20', NULL, '3256');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14725836', '21', NULL, '5412');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '25836914', '22', NULL, '875');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '1998456', '23', NULL, '8563');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '12345698', '24', NULL, '215');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14000001', '25', NULL, '9514');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '12987456', NULL, '1', '120');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '25385914', NULL, '2', '6320');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '5222910', NULL, '3', '8741');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '28314614', NULL, '4', '412');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14000000', NULL, '5', '632');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '3000000', NULL, '6', '745');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '1234567', NULL, '7', '932');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '2345678', NULL, '8', '145');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14725836', NULL, '9', '632');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '25836914', NULL, '10', '214');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '1998456', NULL, '11', '8520');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '12345698', NULL, '12', '906');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14000001', NULL, '13', '800');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '12987456', NULL, '14', '741');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '25385914', NULL, '15', '950');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '5222910', NULL, '16', '8740');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '28314614', NULL, '17', '8000');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14000000', NULL, '18', '685');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '3000000', NULL, '19', '3210');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '1234567', NULL, '20', '1230');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '2345678', NULL, '21', '8521');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14725836', NULL, '22', '6321');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '25836914', NULL, '23', '2584');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '1998456', NULL, '24', '950');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '12345698', NULL, '25', '650');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '14000001', NULL, '26', '840');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '12987456', NULL, '27', '782');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '25385914', NULL, '28', '365');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '5222910', NULL, '29', '9320');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('3/3/2010', NULL, '28314614', NULL, '30', '9500');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('1/1/2019', NULL, '1998456', '1', NULL, '60');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('1/1/2019', NULL, '28314614', '14', NULL, '950');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('1/1/2019', NULL, '12987456', NULL, '2', '8500');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('1/1/2019', NULL, '1998456', '23', NULL, '9000');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('1/1/2019', NULL, '25385914', '6', NULL, '1200');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('1/1/2019', NULL, '1998456', '19', NULL, '300');
INSERT INTO dueno_historico (fecha_registro, significado, coleccionista_documento_identidad, coleccionable_id, comic_id, precio_dolar) VALUES ('1/1/2019', NULL, '12987456', NULL, '7', '1000');

INSERT INTO "local" (nombre, lugar_id, coleccionista_documento_identidad, tipo) VALUES ('La Cupula', '21', NULL, 'Alquilado');
INSERT INTO "local" (nombre, lugar_id, coleccionista_documento_identidad, tipo) VALUES ('La Esquina', '22', NULL, 'Alquilado');
INSERT INTO "local" (nombre, lugar_id, coleccionista_documento_identidad, tipo) VALUES ('El Estadio', '24', NULL, 'Alquilado');
INSERT INTO "local" (nombre, lugar_id, coleccionista_documento_identidad, tipo) VALUES ('The Gathering', '30', NULL, 'Alquilado');
INSERT INTO "local" (nombre, lugar_id, coleccionista_documento_identidad, tipo) VALUES ('The Park', '32', NULL, 'Alquilado');
INSERT INTO "local" (nombre, lugar_id, coleccionista_documento_identidad, tipo) VALUES ('Fomage', '36', NULL, 'Alquilado');
INSERT INTO "local" (nombre, lugar_id, coleccionista_documento_identidad, tipo) VALUES ('Bien Sur', '37', '25385914', 'De un Miembro');
INSERT INTO "local" (nombre, lugar_id, coleccionista_documento_identidad, tipo) VALUES ('Palace', '42', '14000000', 'De un Miembro');
INSERT INTO "local" (nombre, lugar_id, coleccionista_documento_identidad, tipo) VALUES ('Cote', '27', '2345678', 'De un Miembro');

INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '1', '1', '25385914', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '2', '2', '5222910', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '3', '3', '28314614', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '4', '4', '14000000', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '5', '5', '3000000', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '6', '6', '1234567', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '7', '7', '2345678', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '8', '8', '14725836', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '9', '9', '25836914', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '1', NULL, '1998456', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '1', NULL, '12345698', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '4', NULL, '14000001', NULL);
INSERT INTO membresia (fecha_ingreso, fecha_retiro, club_id, club_id_ider, coleccionista_documento_identidad, email_contacto) VALUES ('3/3/2010', NULL, '3', NULL, '12987456', NULL);

INSERT INTO organizacion_caridad (nombre, mision) VALUES ('Cruz Roja', 'Salud');
INSERT INTO organizacion_caridad (nombre, mision) VALUES ('Casa de Ronald MacDonald', 'Por el bienestar de los chicos');
INSERT INTO organizacion_caridad (nombre, mision) VALUES ('Lynn Sage Cancer Research Foundation', 'Prevencion del Cancer');
INSERT INTO organizacion_caridad (nombre, mision) VALUES ('Medicos Sin Fronteras', 'Ayuda a paises tercermundistas');
INSERT INTO organizacion_caridad (nombre, mision) VALUES ('UNICEF', 'Ayuda a los chicos');
INSERT INTO organizacion_caridad (nombre, mision) VALUES ('Rockeffeler Foundation', 'Ayuda a los mas necesitados');
INSERT INTO organizacion_caridad (nombre, mision) VALUES ('Ford Foundation', 'Fundacion de la familia Ford');
INSERT INTO organizacion_caridad (nombre, mision) VALUES ('Wellcome Trust', 'Investigacion Biomedica');
INSERT INTO organizacion_caridad (nombre, mision) VALUES ('Bill and Melinda Gates Foundation', 'Educacion');

INSERT INTO subasta (fecha, hora_inicio, hora_cierre, tipo, caridad, cancelado, local_id) VALUES ('1/1/2011', '14:00', '18:00', 'Presencial', FALSE, TRUE, '1');
INSERT INTO subasta (fecha, hora_inicio, hora_cierre, tipo, caridad, cancelado, local_id) VALUES ('1/1/2012', '14:00', '18:00', 'Presencial', FALSE, TRUE, '2');
INSERT INTO subasta (fecha, hora_inicio, hora_cierre, tipo, caridad, cancelado, local_id) VALUES ('1/1/2013', '14:00', '18:00', 'Presencial', FALSE, TRUE, '3');
INSERT INTO subasta (fecha, hora_inicio, hora_cierre, tipo, caridad, cancelado, local_id) VALUES ('1/1/2014', '14:00', '18:00', 'Presencial', FALSE, TRUE, '4');
INSERT INTO subasta (fecha, hora_inicio, hora_cierre, tipo, caridad, cancelado, local_id) VALUES ('1/1/2015', '14:00', '18:00', 'Presencial', FALSE, TRUE, '5');
INSERT INTO subasta (fecha, hora_inicio, hora_cierre, tipo, caridad, cancelado, local_id) VALUES ('1/1/2016', '14:00', '18:00', 'Presencial', FALSE, TRUE, '6');
INSERT INTO subasta (fecha, hora_inicio, hora_cierre, tipo, caridad, cancelado, local_id) VALUES ('1/1/2017', '14:00', '18:00', 'Presencial', FALSE, TRUE, '7');
INSERT INTO subasta (fecha, hora_inicio, hora_cierre, tipo, caridad, cancelado, local_id) VALUES ('1/1/2018', '14:00', '18:00', 'Presencial', FALSE, TRUE, '8');
INSERT INTO subasta (fecha, hora_inicio, hora_cierre, tipo, caridad, cancelado, local_id) VALUES ('1/1/2019', '14:00', '18:00', 'Virtual', TRUE, TRUE, NULL);

INSERT INTO org_inv (subasta_id, club_id_org, club_id_inv) VALUES ('9', '1', NULL);
INSERT INTO org_inv (subasta_id, club_id_org, club_id_inv) VALUES ('9', NULL, '3');

INSERT INTO org_sub (porcentaje, monto_recibido, organizacion_caridad_id, subasta_is) VALUES ('10', '2101', '9', '9');

INSERT INTO participante (id_inscripcion, subasta_id, membresia_coleccionista_documento_identidad, membresia_club_id, membresia_fecha_ingreso, autorizado) VALUES ('1', '9', '25385914', '1', '3/3/2010', TRUE);
INSERT INTO participante (id_inscripcion, subasta_id, membresia_coleccionista_documento_identidad, membresia_club_id, membresia_fecha_ingreso, autorizado) VALUES ('2', '9', '1998456', '1', '3/3/2010', TRUE);
INSERT INTO participante (id_inscripcion, subasta_id, membresia_coleccionista_documento_identidad, membresia_club_id, membresia_fecha_ingreso, autorizado) VALUES ('3', '9', '12345698', '1', '3/3/2010', TRUE);
INSERT INTO participante (id_inscripcion, subasta_id, membresia_coleccionista_documento_identidad, membresia_club_id, membresia_fecha_ingreso, autorizado) VALUES ('4', '9', '28314614', '3', '3/3/2010', TRUE);
INSERT INTO participante (id_inscripcion, subasta_id, membresia_coleccionista_documento_identidad, membresia_club_id, membresia_fecha_ingreso, autorizado) VALUES ('5', '9', '12987456', '3', '3/3/2010', TRUE);

INSERT INTO listado (orden, precio_base_dolar, precio_vendido_dolar, subasta_id, dueno_historico_id, dueno_historico_coleccionista_documento_identidad, dueno_historico_fecha_registro, participante_subasta_id, participante_id_inscripcion, duracion_min) VALUES (1, '1', '30', '60', '9', '1', '25385914', '3/3/2010', '2', '9', '265');
INSERT INTO listado (orden, precio_base_dolar, precio_vendido_dolar, subasta_id, dueno_historico_id, dueno_historico_coleccionista_documento_identidad, dueno_historico_fecha_registro, participante_subasta_id, participante_id_inscripcion, duracion_min) VALUES (2, '2', '800', '950', '9', '14', '25385914', '3/3/2010', '4', '9', '265');
INSERT INTO listado (orden, precio_base_dolar, precio_vendido_dolar, subasta_id, dueno_historico_id, dueno_historico_coleccionista_documento_identidad, dueno_historico_fecha_registro, participante_subasta_id, participante_id_inscripcion, duracion_min) VALUES (3, '3', '6500', '8500', '9', '27', '25385914', '3/3/2010', '5', '9', '265');
INSERT INTO listado (orden, precio_base_dolar, precio_vendido_dolar, subasta_id, dueno_historico_id, dueno_historico_coleccionista_documento_identidad, dueno_historico_fecha_registro, participante_subasta_id, participante_id_inscripcion, duracion_min) VALUES (4, '4', '10000', NULL, '9', '10', '1998456', '3/3/2010', NULL, NULL, '265');
INSERT INTO listado (orden, precio_base_dolar, precio_vendido_dolar, subasta_id, dueno_historico_id, dueno_historico_coleccionista_documento_identidad, dueno_historico_fecha_registro, participante_subasta_id, participante_id_inscripcion, duracion_min) VALUES (5, '5', '8600', '9000', '9', '23', '1998456', '3/3/2010', '4', '9', '265');
INSERT INTO listado (orden, precio_base_dolar, precio_vendido_dolar, subasta_id, dueno_historico_id, dueno_historico_coleccionista_documento_identidad, dueno_historico_fecha_registro, participante_subasta_id, participante_id_inscripcion, duracion_min) VALUES (6, '6', '8600', NULL, '9', '36', '1998456', '3/3/2010', NULL, NULL, '265');
INSERT INTO listado (orden, precio_base_dolar, precio_vendido_dolar, subasta_id, dueno_historico_id, dueno_historico_coleccionista_documento_identidad, dueno_historico_fecha_registro, participante_subasta_id, participante_id_inscripcion, duracion_min) VALUES (7, '7', '950', '1200', '9', '6', '1234567', '3/3/2010', '1', '9', '265');
INSERT INTO listado (orden, precio_base_dolar, precio_vendido_dolar, subasta_id, dueno_historico_id, dueno_historico_coleccionista_documento_identidad, dueno_historico_fecha_registro, participante_subasta_id, participante_id_inscripcion, duracion_min) VALUES (8, '8', '150', '300', '9', '19', '1234567', '3/3/2010', '2', '9', '265');
INSERT INTO listado (orden, precio_base_dolar, precio_vendido_dolar, subasta_id, dueno_historico_id, dueno_historico_coleccionista_documento_identidad, dueno_historico_fecha_registro, participante_subasta_id, participante_id_inscripcion, duracion_min) VALUES (9, '9', '950', '1000', '9', '32', '1234567', '3/3/2010', '5', '9', '280');

INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Borderlands: Origins',1,9781613776,'2013/06/04',8,'TRUE','La serie se adentra en los origenes de cada uno de los cuatro cazadores boveda en Borderlands, previo a su llegada a Pandora y embarque Marcus Kincaid bus.',104,'TRUE','Mikey Neumann');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Modern Warfare 2: Ghost',1,9781567776,'2009/01/01',12,'TRUE','El brutal relato del misterioso soldado de asalto conocido como Ghost. Descubre las motivaciones del sargento Riley y su intervencion en conflictos que les llevaran desde el Reino Unido hasta Afganistan',144,'TRUE','David Lapham');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Cyberpunk 2077: Trauma Team',1,9783757776,'2020/09/09',13,'TRUE','Es una historia de guerra, de trastornos de estres, de lealtad, de amor, y tambien de odio y de violencia, de injusticias, pero, sobre todo, es una montana rusa de violencia y disparos.',96,'TRUE','Cullen Bunn');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Deus Ex: Human Revolution ',1,9783759876,'2011/01/01',3,'TRUE','En un futuro no muy distante, la Humanidad se ve amenazada por el imparable avance de la tecnología y los gobiernos opresores que controlan a la ciudadania, asi que nuestro heroe y su arsenal seran la unica salvacion posible.',103,'TRUE','Robbie Morrison');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Gears of war',1,9783759986,'2018/12/18',7,'TRUE','Cerrando la brecha entre Gears of War 1 y 2, sigue las brutales aventuras de Marcus Fenix ??y Delta Squad en la batalla contra las langostas! Descubra lo que sucedio despues del Bombardeo de Masa Ligera y como reaccionaran las langostas a esta devastadora arma.',320,'TRUE','Joshua Ortega');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Gears of war',2,9783759456,'2019/12/17',6,'TRUE','Mientras las Guerras del Pendulo continuan entre la Coalicion de Gobiernos Ordenados y la Union de Republicas Independientes, Marcus Fenix ??y su mano derecha Dominic Santiago se encuentran desplegados en su primera gira militar y deben soportar la dura realidad de la batalla, la perdida y la desaparicion esperanza de victoria.',256,'TRUE','Joshua Ortega');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Gears of war',3,9783759956,'2013/12/10',6,'TRUE','Tras el hundimiento del Jacinto al final del Volumen 2, los Gears han huido a la isla de Vectes, donde luchan por defender los ultimos restos de la humanidad de The Stranded y una nueva amenaza, The Lambent, una forma de vida mortal y mutante.',256,'TRUE','Joshua Ortega');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('God of War: Fallen',1,9783887956,'2021/03/10',2,'TRUE','¿Puede un hombre alguna vez estar libre de su pasado? ¿Podran las mareas del tiempo lavar las arenas sangrientas del pecado? ¿O las transgresiones transpiradas manchan el alma de manera permanente e ineludible? Despues de conquistar a Zeus y frustrar a Atenea, Kratos se cree finalmente libre de su esclavitud.',22,'TRUE','Chris Roberson');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('God of War: Fallen',2,9783927956,'2021/04/12',4,'TRUE','Despues de conquistar a Zeus y frustrar a Atenea, Kratos se cree finalmente libre de su esclavitud. Zarpa hacia el desierto en un intento de distanciarse de su hogar y su vergüenza solo para encontrar que su rabia y culpa lo siguen de cerca.',26,'TRUE','Chris Roberson');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('God of War: Fallen',3,9783347956,'2021/05/05',4,'TRUE','¡Una monstruosa Bestia del Caos amenaza a los temerosos aldeanos del desierto y se enfrenta a Kratos, obligándolo a volver a la batalla! Pero a pesar de su deseo de escapar de su pasado violento, Kratos vuelve a un estado familiar de rabia y furia, lo que desencadena una reacción en cadena de ira interminable por el Fantasma de Esparta.',22,'TRUE','Chris Roberson');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Halo: Fall of Reach',1,9783486796,'2013/01/01',3,'TRUE','El siglo XXVI. La humanidad se ha expandido mas alla del sistema de la Tierra a cientos de planetas que los colonos ahora llaman hogar. Pero el Gobierno de la Tierra Unida y el Comando Espacial de las Naciones Unidas están luchando por controlar este vasto imperio.',23,'TRUE','Brian Reed');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Halo: Fall of Reach',2,9783486796,'2014/12/01',2,'TRUE','El Covenant continua su invasion del planeta Reach, empujando al UNSC a su punto de ruptura, mientras el Jefe Maestro y Cortana luchan por salvar el planeta y la Flota. ¡Este es el capitulo final de la saga Halo: Fall of Reach de Brian Reed y Felix Ruiz!',21,'TRUE','Brian Reed');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Halo: Fall of Reach',3,9783376796,'2015/12/01',2,'TRUE','El Pillar of Autumn y el UNSC se enfrentan a una fuerza masiva del Covenant, mientras el Jefe Maestro y sus compañeros Spartans defienden el planeta Reach. ¡Brian Reed y Felix Ruiz continuan el capitulo final de Halo: Fall of Reach!',24,'TRUE','Brian Reed');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Halo: Helljumper',1,9783455796,'2010/03/10',5,'TRUE','Cuando el planeta colonia Ariel envía una misteriosa senal de socorro, depende de los Helljumpers de la 105a Infantería de Marina comprobarlo, pero pronto dos Helljumpers encuentran su amistad y sus vidas en juego.',120,'TRUE','Peter David');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('The Last of Us American Dreams',1,9783448696,'2013/10/29',12,'TRUE','Hace diecinueve anos, un brote de parasitos fungicos mato a la mayoria de la poblacion del planeta. Ellie, de trece anos, que vive en una de las pocas zonas que permanecen en cuarentena, comienza una nueva vida en un internado militar.',96,'TRUE','Faith Erin Hicks');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Castlevania: The Belmont Legacy',1,9783877696,'2005/03/09',5,'TRUE','La terrorifica sombra de Dracul el Empalador amenaza de nuevo con acabar con la paz en los poblados de Rumania.',112,'TRUE','Mark Adreyko');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('The Legend of Zelda comics: Ocarina of Time',1,9783877236,'2009/09/03',10,'TRUE','Link vive en el bosque Kokiri hasta que su mentor, el Gran Arbol Deku, le envia al mundo exterior antes de morir. El joven aventurero debe encontrar a la princesa Zelda, que le hablara de la Trifuerza y de la ocarina del tiempo',192,'TRUE','Akira Himekawa');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('The Legend of Zelda comics: Majora s Mask',1,9783567236,'2012/09/28',6,'TRUE','Link esta buscando a Navi, la pequena hada que lo acompano en su lucha para salvar Hyrule. Pero por culpa de Skull Kid y de la mascara que lo ha poseido, nuestro joven heroe acaba en la ciudad de Termina, que esta a punto de desaparecer',208,'TRUE','Akira Himekawa');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('The Legend of Zelda comics: Oracle of Seasons',1,9783567976,'2011/02/25',14,'TRUE','La Trifuerza transporta a Link, el heroe del tiempo, a la tierra de Holodrum, donde se encuentra con la hermosa bailarina Din, tambien conocida como el “oraculo de las estaciones”.',388,'TRUE','Akira Himekawa');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('The Legend of Zelda comics: Four swords',1,9783567656,'2017/07/11',9,'TRUE','La historia comienza con Link, que, junto a su padre, son parte de la Guardia Real de Hyrule, sin embargo, Link odia trabajar en equipo y esto causa que el padre de Link pida ayuda a la Princesa Zelda, amiga de la infancia de Link.',370,'TRUE','Akira Himekawa');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Sonic the Hedgehog/Mega Man: Worlds unite',1,9783565456,'2015/04/13',9,'TRUE','Dark forces have come together in the far future! The vicious conqueror Sigma has cheated death again and escaped the justice of X and the Maverick Hunters.',136,'TRUE','Ian Flynn');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Sonic / Mega Man: Worlds Collide',1,9783569215,'2013/12/20',10,'TRUE','¡La epica de Sonic the Hedgehog / Mega Man comienza con una explosion en el primero de los tres volumenes cuando Blue Blur y Blue Bomber se encuentran por primera vez!',104,'TRUE','Ian Flynn');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Dark Souls II: Into the Light',1,9783564829,'2014/01/08',6,'TRUE','Hace mucho, en una tierra amurallada, muy lejos del norte, un gran rey construyo un gran reino. Creo lo que llamaban Drangleic. Un lugar donde las almas curan tu mente enferma. Seras algo más que humano.',24,'TRUE','Rob Williams');
INSERT INTO comic (titulo,volumen,numero,fecha_publicacion,precio_publicacion,color,sinopsis,paginas,cubierta,editor) VALUES ('Tekken Comic',1,9783564832,'2009/10/19',5,'TRUE','Jin Kazama, el dueno de la poderosa corporación japonesa Mishima Zaibatsu, declara la guerra al mundo entero. Las naciones que se pusieron del lado de la corporacion se fusionaron en una nacion independiente, destruyendo cualquier oposicion.',112,'TRUE','Rui Takato');
